### ISSUE TITLE
Inline javascript

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#1]
MongoDB gives possibility to query using javascript. It is somewhat similar to `fragment`. Is there a possibility to use custom functions in queries or only the predefined ones? Is the function apporoach good here? It would look something like this:
```elixir
from u in User,
     where: javascript("this.name == this.username")
```

**Comment by ericmj** [comment]
Mongo only accepts javascript in special locations (it's not a general query expression). Specifically it only seems to be allowed in mapReduce which ecto does not support (yet?) and $where [1].

We could could pass it directly as the value the driver expects (possibly wrapped for ecto), for example: `%BSON.Javascript{code: "this.name == this.username"}`, the `javascript/1` function could return this,

[1] http://docs.mongodb.org/manual/core/server-side-javascript/

**Comment by michalmuskala** [comment]
It's possible to combine regular queries with javascipt [1].

It's basically possible to have a selector like this: 
`{ active: true, $where: "this.credits - this.debits < 0" }`
to select all the documents with field active set to true, and that match the javscript expression.

[1] http://docs.mongodb.org/manual/reference/operator/query/where

**Comment by josevalim** [comment]
When talking to Eric, we thought we could make javascript a value. So we would do:

    js = Mongo.Ecto.javascript("some javascript code")
    from q in Post, where: p.title == "foo" and ^js

@ericmj ?

**Comment by michalmuskala** [comment]
I was thinking about making something like that, and providing all the functions like `javascript`, `regex`, etc. under Mongo.Ecto.Query module, you could import.
You could then do something like:
```elixir
from q in Post, where: ^javascript("this.content.length < 100")
```

**Comment by josevalim** [comment]
@michalmuskala well, if it is a type, I wouldn't necessarily put in `Mongo.Ecto.Query` because they can theoretically be used elsewhere. Can any of regex or javascript be saved as a value for a field in the database?

**Comment by michalmuskala** [comment]
I tried implementing this to support the syntax I mentioned earlier, but I hit a problem with Ecto.

From my understanding it seems that Ecto expects elements passed in where clause to be always convertible to boolean values. I see two solution for this: either modify Ecto to support passing other values to where, or make a new Ecto type to represent javascript that would respond to typecasting to a boolean, but return the `BSON.JavaScript` struct, we would use later in building query.
