### ISSUE TITLE
Regex support

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#10]
MongoDB supports querying text fields with regexes.

Both Elixir and Mongo use PCRE, so we could use Elixir's literal syntax, but I'm not sure that this is a good idea (there might be some unforeseen incompatibilities, and the regexes would be compiled on both sides).
Other way to support these is to provide a `regex` function that would return expected data, similar to the `javascript` we're considering in #1.

**Comment by josevalim** [comment]
It is worth mentioning that we support both `like` and `ilike`? I guess it would be a bad idea to use it though because it is very different from SQL search, right?

**Comment by josevalim** [comment]
Also, if regexes are values (for example, they can be stored in mongo) we should consider a solution similar to #1 too.

**Comment by michalmuskala** [comment]
I've hit similar problem with value conversion as in #1. 
I tried using equality operator but that obviously tried to convert the regex to a string. What I would propose here is for Ecto to support the `=~` operator for matching against a regex.

**Comment by michalmuskala** [comment]
As we discussed regexes will be supported using fragments.
