### ISSUE TITLE
How can I search in an array of maps

### ISSUE THREAD

**Issue by tacnoman** [michalmuskala/mongodb_ecto#102]
Hello guys.
I have in my db an array of maps, like this:

groups = [{group_id: 123, group_name:"nameofMyGroup"}......]

How can  I do to search by a group_id in field groups?

I tried this:

```elixir
query = from p in Project,
where: Enum.any?(p.groups, fn x -> x["group_id"] == my_group_id end),
select: p
```

But this does not work.
How can I do to search in array of maps?

Thanks!

**Comment by michalmuskala** [comment]
You can't use elixir functions in database queries.

You can use `fragment` to insert raw database syntax into the ecto generated queries. In that case that would be:
```elixir
from p in Project,
  where: fragment(["groups.group_id": my_group_id]),
  select: p
```

What (more or less) corresponds to the query document in mongo:
```javascript
db.projects.find({"groups.group_id": my_group_id})
```
