### ISSUE TITLE
Failed to use "ecto" (versions 2.1.0 to 2.1.3)

### ISSUE THREAD

**Issue by MaraniMatias** [michalmuskala/mongodb_ecto#105]
Hello, I have a problem.
Failed to use "ecto" (versions 2.1.0 to 2.1.3) because
  mongodb_ecto (version 0.1.5) requires ~> 1.0.0
  phoenix_ecto (version 3.2.1) requires ~> 2.1

Failed to use "ecto" (versions 1.0.0 to 1.0.7) because
  phoenix_ecto (version 3.2.1) requires ~> 2.1
  mix.exs specifies ~> 1.0.0

Thank you.

**Comment by maennchen** [comment]
Have a look at #91 

This library is not yet compatible to Ecto 2.

**Comment by MaraniMatias** [comment]
Thank you.
Then I will change the versions of phoenix_ecto.
     {:phoenix_ecto, "~> 1.2"},
     {:mongodb_ecto, "~> 0.1.5"}
