### ISSUE TITLE
Enable ssl connection with ecto 2.0

### ISSUE THREAD

**Issue by Slavenin** [michalmuskala/mongodb_ecto#108]
Hi! How i can connect to my mongodb instanse with ssl parameter in true?
I have dsn string like mongodb://user:pass@host:port/?ssl=true and i can not disable ssl. 
How i can connect with this parameters?

**Comment by ankhers** [comment]
You can either break that apart into its different pieces. Something like

```
config :my_app, MyApp.Repo,
  adapter: Mongo.Ecto,
  username: "user",
  pass: "pass",
  hostname: "host",
  port: 27017,
  ssl: true
```

Or, you can take advantage of using the `url` option.

```
config :my_app, MyApp.Repo
  adapter: Mongo.Ecto,
  url: "mongodb://user:pass@host:port/?ssl=true"
```

The unfortunate thing about this is that the current release of the actual [`mongodb`](https://github.com/ericmj/mongodb) package does not have SSL support. So you will need to grab that from github

**Comment by Slavenin** [comment]
Tnx! With "url" parametr not work.
With config like:
```
config :crawler, Crawler.MongoRepo,
  adapter: Mongo.Ecto,
  database: "cache",
  username: "cache",
  password: "***",
  hostname: "***",
  port: ***,
  ssl: true
```
>15:58:21.258 [error] Mongo.Protocol (#PID<0.340.0>) failed to connect: ** (Mongo.Error) ssl connect: TLS connection is closed - :closed

instance mongodb created in ms azure

**Comment by ankhers** [comment]
You are going to want to file an issue with the [`mongodb`](https://github.com/ericmj/mongodb) package. That is where the SSL functionality is implemented.
