### ISSUE TITLE
Support for Mongoid's localize option internally

### ISSUE THREAD

**Issue by Bharat311** [michalmuskala/mongodb_ecto#114]
In my Project, there are a lot of fields which require localization of the data input by a user.

Earlier, I was using Mongoid with Rails and it was as easy as adding `localize: true` option to the `field`.

I believe we can easily achieve the same in this package also, using the `:map` option for the field value and defining a macro that allows us to define a field as a localized field.

If we feel this is needed and could be included in the package itself, we can decide upon how the spec looks like and what is the best way to implement the same.

One suggestion:

```
defmodule Demo.User do
  use Demo.Web, :model

  schema "users" do
    localized_field :first_name, :string
    localized_field :last_name, :string
  end
end
```

I'd be happy to work on a PR for the same.

**Comment by johnnyshields** [comment]
@Bharat311 I think:

```
field :last_name, :localized_string
```

is better

**Comment by michalmuskala** [comment]
I don't see how this would be implemented at the data-type level - a map field is just that, a field. It can't have behaviour attached.

This would also require global state for storing current locale, which is not possible (closest thing is process dictionary - this is actually used by Gettext, but is process local).

Probably the best way to do this, would be to provide functions to working with localised data, I could imagine interface like:
```
Localised.set_locale(:en)
Localised.get(struct, field)
Localised.set(struct, field, value)
```

There's a possible integration with ecto that would allow for:
```
schema
|> Ecto.Changeset.cast(params, non_localised_fields)
|> Localised.cast(localised_fields)
```

There's nothing specific to mongodb in those, though. As such I'm closing this as it's not really actionable in here.
