### ISSUE TITLE
Not compactable with latest version

### ISSUE THREAD

**Issue by dheenaINDIAN** [michalmuskala/mongodb_ecto#117]
Help us in solving the issue

Failed to use "ecto" because
mongodb_ecto (version 0.1.5) requires ~> 1.0.0

**Comment by ankhers** [comment]
Can you please post your dependencies list in your mix file?

**Comment by dheenaINDIAN** [comment]
defp deps do
    [{:phoenix, "~> 1.2.1"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.6"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:mongodb_ecto, "~> 0.1"}

**Comment by ankhers** [comment]
The current released versions of `mongodb_ecto` do not support the more recent versions of ecto. There is a PR #84 that gets this adapter working with ecto 2.0. You can use it by modifying your `mongodb_ecto` like so `{:mongodb_ecto, github: "michalmuskala/mongodb_ecto", branch: "ecto-2"}`. There are a number of people, myself included, that are using it in production.

If you go that route, you will also need to tell mix to use a specific version of ecto, `{:ecto, "~> 2.0", override: true}`.
