### ISSUE TITLE
Is Possível use bulk_write?

### ISSUE THREAD

**Issue by allanbatista** [michalmuskala/mongodb_ecto#121]
Hi, is possible to use bulk_write with mongo_ecto?

**Comment by ankhers** [comment]
Unfortunately not. The underlying [`mongodb`](https://github.com/ericmj/mongodb) driver does not currently support it.

Fortunately, it is on the [immediate roadmap](https://github.com/ericmj/mongodb#immediate-roadmap). So it will (hopefully) get done soon. If it is something that you need and are willing to help out with the project, there is a ticket (ericmj/mongodb#126) in the tracker to track the progress of bulk write.
