### ISSUE TITLE
Mongo driver should accept keyword lists in multiple places

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#15]
We are creating this here but the changes go to the driver. /cc @ericmj

**Comment by ericmj** [comment]
Where is it missing?

**Comment by josevalim** [comment]
I thought the plan was to allow documents to be keyword lists too... or am I just super confused?

**Comment by josevalim** [comment]
According to @ericmj this already works, you just need to be careful to not pass an empty list.
