### ISSUE TITLE
Add map operations to Ecto

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#17]
We need to compare which operations are supposed by both Mongo and [Postgres](http://www.postgresql.org/docs/9.4/static/functions-json.html) and discuss which ones should be added to Ecto.

**Comment by josevalim** [comment]
@michalmuskala I will leave it up to you to define which operations we should support and the syntax for such. :)

**Comment by michalmuskala** [comment]
@josevalim what do you have in mind? Query and selection syntax on the map type or something else?

**Comment by josevalim** [comment]
@michalmuskala I don't have anything in mind. :) We just need to compile a list of operators that are available in both postgres and mongo and then discuss which ones are worth adding. :)

**Comment by michalmuskala** [comment]
First thing we can support in both Mongo and Postgres can be selecting a nested value:
```elixir
from p in Post, select: {p.id, p.meta.name, p.meta.array[0]}
from p in Post, select: {p.id, p.meta[:name], p.meta[:array][0]}
```
I don't like selecting a value within array like that, but `array.0` is a compile error, and I couldn't think of a better syntax. From the two syntaxes above I think I prefer the second one - it's more obvious we are dealing with a map. But both are fine.

For Postgres we can use the `#>` operator to get inside the field and retrieve the value:
`p.meta[:array][0]` would translate to `p0.meta #>'{array, 0}'`

For Mongo we can use projection to specify which fields are we interested in, but that gives us the document anyway - we can use the path to retrieve the values later in the adapter.

**Comment by michalmuskala** [comment]
One more important thing. 
Postgres will return `NULL` if a field does not exists.
Mongo will not return the field at all, so we can turn it to `nil` too.

@josevalim @ericmj thoughts?

**Comment by ericmj** [comment]
We should convert it to nil, we have to if you are selecting the field into a tuple or list.

**Comment by michalmuskala** [comment]
There's just one problem with that, I realized just now:

In Mongo with a query `from p in Post, select: {p, p.meta.name}` we can't just generate a projection based on the fields.
Simply generated projection `%{"meta.name": 1}` will give us a document: `%{meta: %{name: value}}`.
Expanding the projection to specify every field as I did in #20 will give us other fields from the top document, but will still only include the `name` key in the `meta` nested map.

One solution to that problem is not to add this field to the projection and request whole document, and only select what we want in the adapter when processing the result.
The similar solution should be used for a query `from p in Post, select: {p.meta, p.meta.name}`, when we want both the whole nested map, and just one field from it.
The behaviour would be different for a query `from p in Post, select: p.meta.name` where we would specify the field in projection, since we don't care about the other fields in the nested map.

**Comment by josevalim** [comment]
@michalmuskala I think the solution could be done by generating trees and merge them. Those trees can be built with maps for simplicity. Imagine the following... if you have the fields:

    [p, p.meta, p.meta.bar]

which I will express as a list of lists for simplicity:

    [[], [:meta], [:meta, :bar]]

Now you need to traverse them, generating maps, merging them and then calculate the path. This code would do it:

```
defmodule Foo do
  def generate(fields) do
    to_path Enum.reduce fields, %{}, fn field, acc ->
      deep_merge(field_to_map(field), acc)
    end
  catch
    :root_included ->
      # If there is p, we always include all fields
      # if there is a model, otherwise no projection.
      [[:field_a, :field_b, :field_c]]
  end

  defp to_path(map) do
    case Enum.to_list(map) do
      [] -> []
      [{key, value}] -> [key|to_path(value)]
      [_|_] = list -> [Enum.map(list, &elem(&1, 0))]
    end
  end

  # If there is a p, just abort.
  defp field_to_map([]) do
    throw :root_included
  end

  defp field_to_map(list) do
    Enum.reduce Enum.reverse(list), %{}, fn x, acc ->
      Map.put(%{}, x, acc)
    end
  end

  defp deep_merge(v1, v2) do
    Map.merge(v1, v2, fn k, d1, d2 -> deep_merge(d1, d2) end)
  end
end

# p is included, so all fields in p should be returned, something like [[:field_a, ...]]
IO.inspect Foo.generate([[], [:meta], [:meta, :name]])

# it should be [:meta, [:name, :another]]
IO.inspect Foo.generate([[:meta, :name], [:meta, :another]])

# it should be [:meta, :another]
IO.inspect Foo.generate([[:meta, :another]])

# it should be [:meta]
IO.inspect Foo.generate([[:meta]])

# I.e. each entry in the list is a nesting... if an entry in the list is another
# list, those are all the entries
```

**Comment by michalmuskala** [comment]
Regarding queries on maps.

With Postgres the syntax is exactly the same as when selecting fields. We can do things like:
`WHERE p0.meta #> '{array,0}' >= '5'`, and all operators should work normally.

With Mongo, we can use dot notation for querying nested field, so in that case that would be `["meta.array.0": ["$gte": 5]]`

With Mongo we get some special operators, but we could support them with fragments.

**Comment by michalmuskala** [comment]
Unless this is added to Ecto itself, we can't do much here.
