### ISSUE TITLE
Dynamic Attributes

### ISSUE THREAD

**Issue by mgwidmann** [michalmuskala/mongodb_ecto#18]
Mongo is schemaless, and so it doesn't enforce any particular fields to be defined or with their types known. If fact, the same key within the same collection can all hold different types for each record. This is one of Mongo's strengths and Ecto should be careful not to take that away. Currently an Ecto model is strict about which fields it has (defined in the `schema` macro block). However, there are times which it is necessary to say a particular model will not define its schema and will be open to "dynamic attributes". This is an extremely powerful feature of Mongo.

Heres an example from Mongoid:

```ruby
class User
  include Mongoid::Document
  embeds_one :preferences, class_name: 'Preference'
  field :name
end
class Preference
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  embedded_in :user
end

User.create(name: 'User', preferences: {notify_on_something: true, notify_on_something_else: false})
#   MOPED: 127.0.0.1:27017 INSERT       database=myapp_development collection=users documents=[{"_id"=>BSON::ObjectId('558ac0114d617453740d0000'), "name"=>"User", "preferences"=>{"_id"=>BSON::ObjectId('558ac0114d617453740e0000'), "notify_on_something"=>true, "notify_on_something_else"=>false}}] flags=[]
```

This is more than just saying that the `preferences` field is of type `Map`. We have full support of adding validations, callbacks, ect. For example, if we only wanted to allow boolean flags, we could validate all fields are of type boolean, but we allow any number of keys. Or we could write a custom validation to limit the number of keys within the preferences model. Lots of power is obtainable here by sometimes being less strict. Sometimes the data structure is less known at development time and this is exactly where Mongo shines.

As a side note, Mongoid does also not require that the type of any particular field be described in the schema block. While less useful, it is still an ability Mongo has that we wouldn't want to restrict via Ecto. The `User` model above has a field `:name` which doesnt have a type as an example. We could store a string (for just one name), or a map (for splitting out first/last names, ect, which can happen sometimes as the code evolves) in this field if we chose to do so.

**Comment by josevalim** [comment]
> While less useful, it is still an ability Mongo has that we wouldn't want to restrict via Ecto. 

If you are declaring a model then we are going to require field names and types. The whole point of Ecto is to make it easy to map data in your database to a struct in a type safe way. So while we lose some dynamic features, we win on the side of guarantees.

If you want dynamic features, then surely, you don't want to declare a model and instead work directly with maps. Opposite to Ruby, structs in Elixir require the given fields at *compile* time and you can't change them at runtime.

However, I would love to make parts of Ecto more dynamic when required. For example, some flexibility may be required on the changesets side. On other parts, we already do a good job, today you can even query unstructured data with Mongo+Ecto:

    from p in "posts", where: ..., select: p.name

And we plan to support this next:

    from p in "posts", where: ..., select: p

**Comment by mgwidmann** [comment]
@josevalim The purpose of the dynamic attributes is to allow unstructured data while still having the power of callbacks, validations, ect. 

Even still, there will be cases where data comes back which is not defined in the model. Ecto should allow the user to choose to drop the data or not (default can be fine to drop it to be more strict). The remaining data can be updated like so:

```elixir
defmodule Dynamic do
  defstruct something: nil
end

d = %Dynamic{} |> Map.put :another, "data"
# %{__struct__: Dynamic, another: "data", something: nil}
```

**Comment by ericmj** [comment]
@mgwidmann We shouldn't put keys on structs that weren't there when defining it. It breaks all assumptions about struct, for example you can see that inspects wrong.

If you want unstructured data I would suggest declaring a map field where you can put any keys.

**Comment by mgwidmann** [comment]
@ericmj Mongo is very different. Using just a map means you lose validations and callbacks. Trust me when I say this is an important feature. I've used several ODM's with Mongo and these reasons are why Ruby is still, no contest, currently the best choice for interaction with Mongo.

Java for example has the same philosophy, and I have personally seen data lost in production because of this. Please reconsider.

**Comment by josevalim** [comment]
@mgwidmann we can't reconsider because that's how the **language** was designed and that is not changing. Structs are defined at compilation time by definition, you must not add new keys otherwise you no longer have that struct.

As said, I would love to make some things in Ecto more dynamic and part of the Google Summer of Code work is exactly about that, but if you require dynamic access from top to bottom then Ecto is not going to be your cup of tea when working with Mongo.

**Comment by mgwidmann** [comment]
@scottmessinger do you have any feelings about not supporting this? 

I'd like to hear from another fellow Mongo developer how they feel.

**Comment by ericmj** [comment]
It's not a question about we not wanting to support it or not. We *can't* support it because structs (from the word structured) do not allow unstructured data.

**Comment by ericmj** [comment]
We could do some special handling of dynamic fields. When we retrieve the document we can put all attributes that do not fit on the struct in a `:dynamic` field of map type, when we save the model we can injecting everything from `:dynamic` back into the document.

It's quite a hacky workaround, I don't like it very much, but at least you wouldn't lose data.

**Comment by josevalim** [comment]
There are other things we could do. For example, store the `__meta__` data field in the Preferences map but not make it a struct. This would at least allow us to run callbacks for non-structured data which is part of the complain here. But I agree this won't be the focus right now. And you can always run the callbacks on the model that embeds the non-structured one.

**Comment by scottmessinger** [comment]
@mgwidmann I don't use dynamic attributes much myself, but I agree that they're important for many use cases of MongoDB. I'd imagine that if someone has a largely dynamic attributes use case, dropping down to the driver might be a better choice. Regardless, in order of priority, I'd put:

1. Not overwriting dynamic attributes
2. Writing dynamic attributes
3. Validations & Callbacks.

I don't know how to solve 2 and 3, but as for 1, that should be pretty easy. Mongoid made the choice a while ago to make all updates use `$set` instead of just overwriting the entire doc. E.g.
```
// This:
`db.find(...).update({$set: {field1: value1, field2: value2}})

// Instead of
$db.find(...).update({field1: value1, field2: value2})
```

The former only updates values in $set. The latter replaces the entire document. If the mongodb_ecto adapter uses the `$set` technique, dynamic attributes won't be overwritten on updates.
