### ISSUE TITLE
$exists queries

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#2]
MongoDB support query where we ask for presence of a field in a document. I think this would be good as a function, similar to inline javascript. The null value and existence of a field are two separate issues, so `is_nil`, won't be a good solution.
I'm thinking of something like this:
```elixir
from u in User,
     where: exists(u.name)
```

**Comment by josevalim** [comment]
I think this one could be supported by the fragment syntax for now. So I would close this in favor of #5. In the future, we can start adding those directly to Ecto, if more and more adapters need them.

**Comment by michalmuskala** [comment]
As suggested closing in favour of #5 and fragments.
