### ISSUE TITLE
Use the new Ecto.Adapters.Pool

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#21]
We have just merged it into master.

**Comment by michalmuskala** [comment]
@josevalim I'm not sure what I'm supposed to do in that case: https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto.ex#L76

I tried to mirror the SQL adapter, but I'm not sure that's the right thing. With logging in place I will have some string representation of the query, should it be used here?
