### ISSUE TITLE
Discuss if maps and embeds should use $set or "$replace"

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#23]
While ideally we would use `$set`, we may not be able to emulate this operation on SQL databases. So we need to find a good middle ground. We may also have different behaviour depending on map or embed. So I have opened this for discussion.

**Comment by ericmj** [comment]
For embedded we should use $set and for maps a full replace. Even if SQL databases cannot do $set.

**Comment by michalmuskala** [comment]
To clarify: with mongo to replace a nested structure you do a `$set` with entire structure, eg:
```
{"nested": {"map": 1}}
update({"$set": {"nested": {"value": 5}}})
{"nested": {"value" 5}}
```

I agree with Eric, that we should do as many partial updates as possible to reduce eventual data loss. With maps we retrieve all keys, so it should be fine to update everything (disregarding concurrency problems), with nested models we would keep only fields defined in a model - we would loose all other fields with replacing everything.

**Comment by josevalim** [comment]
Ok, I have opened an issue in Ecto so we make sure to have tests for the current set behaviour, which is the default for all dbs. @michalmuskala just needs to write a test for things like `set: ["foo.0.bar": 3]` and we can close this.

**Comment by michalmuskala** [comment]
@josevalim I tried testing updating nested fields and it's not working. I get an error:
```
** (Ecto.QueryError) deps/ecto/lib/ecto/repo/queryable.ex:79: field `Ecto.Integration.Post.meta.foo` in `update` does not exist in the model source in query:
     
     from p in Ecto.Integration.Post,
       where: p.id == ^"1d231a736577e406cbe999a3",
       update: [set: ["meta.foo": ^"new"]]
```
I tracked it down to `Ecto.Query.Planner.type!/5` - Ecto tries to get the type of the "meta.foo" field that obviously doesn't exist. I tried to figure out some solution, but everything I game up with - I didn't like.

**Comment by josevalim** [comment]
We don't have a nested fetch/update syntax yet. Today we discussed:

    from p in Post, select: p.comments[0].title
    from p in Post, update: [set: [{p.comments[0].title, "foo"}]]

And dynamically it would look like:

    from p in Post, select: field(p.comments[^ix], ^field)
    from p in Post, update: [set: [{field(p.comments[^ix], ^field), "foo"}]]

However, we are not confident on this yet, so let's wait a bit.
