### ISSUE TITLE
(UndefinedFunctionError) undefined function: Simple.Repo.__pool__/0

### ISSUE THREAD

**Issue by robinsound** [michalmuskala/mongodb_ecto#24]
Running 'simple' example:
** (Mix) Could not start application simple: Simple.App.start(:normal, []) returned an error: shutdown: failed to start child: Simple.Repo
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: Simple.Repo.__pool__/0
            (simple) Simple.Repo.__pool__()
            (mongodb_ecto) lib/mongo_ecto.ex:333: Mongo.Ecto.start_link/2
            (stdlib) supervisor.erl:314: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:297: :supervisor.start_children/3
            (stdlib) supervisor.erl:263: :supervisor.init_children/2
            (stdlib) gen_server.erl:306: :gen_server.init_it/6
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

I'm trying to create a project with Postgres Phoenix (PgRepo) and Mongo (MongoRepo), but I was going the same exception.
With PgRepo no problem, but when I try MongoRepo.start_link, it gives the same error when I run the 'Simple' example

I Check commit 'Update ecto, correct handling pool' and thought it was resolved. 
Sorry if you're in it.

**Comment by michalmuskala** [comment]
There was an issue with versions of ecto used in the adapter and in the sample app. I made sure we will test both the adapter and the sample app as part of our CI build, so a situation like that should never happen again.

Thank you for reporting!
