### ISSUE TITLE
Do not send nil values on insert if the field default is also nil

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#26]
This should be handled by the adapter so we need to figure out which information to pass in the callbacks.

**Comment by michalmuskala** [comment]
One options for this would be to pass the model - I could generate a new struct in the adapter and compare them. Other solution would be to expose default values through `__schema__` reflections.

**Comment by josevalim** [comment]
@michalmuskala yeah, you can get the default values by calling `__struct__` in the model. I think that is the way to go. Can you please change Ecto so it passes {binary, model} to insert/update/delete? model should be nil if there is no model (i.e. the same as we receive in all/update_all/delete_all).

**Comment by josevalim** [comment]
actually, we can only do insert/update/delete with model, so it will always be there.

**Comment by josevalim** [comment]
Just send another PR to Ecto while I get the other one reviewed. :)
