### ISSUE TITLE
Fields that are not specified in a model

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#3]
What should we do about them? Maybe something to mark a field optional? I think this is one of the main selling points of MongoDB, so it would be a pity not to support this. I'm not sure how big of an impact would that have on Ecto. I was thinking about something like this:
```elixir
schema "users" do
  field :name, :string, optional: true
end
```
Then when the field won't exists we would get a struct without that key.

**Comment by ericmj** [comment]
I don't think we should support this. We should treat all fields as optional, if it doesn't exist in the document we retrieve we set the field as `nil`. This way we can also chose to not persist fields with `nil` values so that we store more compact documents. Most Mongo ORMs do this.

**Comment by michalmuskala** [comment]
And what about the fields that are not specified in a model? Should we just drop them when we get them from the database?

**Comment by ericmj** [comment]
Yes, there's nothing we can do about those fields since you shouldn't add extra fields to structs. Ecto supports querying with a source without a model which we could use to retrieve full documents.

**Comment by josevalim** [comment]
:+1: to everything @ericmj said. If it is in the model, we use it, otherwise, we discard it.
