### ISSUE TITLE
Figure out how to perform nested updates in Ecto

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#30]
Today's syntax:

    from p in Post, update: [set: ["field.nested.really": bar]]

Does not work due to the type checker.

**Comment by michalmuskala** [comment]
What if we used a tuple for this:
```
{:"field.nested.really", [:field, :nested, :really]}
```
So we have both the db-level information, and the language-level information. We'll be able to type check expressions like this. We could use a simple macro to ease creation of these:
```
nested(field.nested.really)
```
In that case it may be more convenient to use map syntax:
```
from p in Post, update: [set: [{nested(field.nested.really), bar}]]
from p in Post, update: [set: %{nested(field.nested.really) => bar}]]
```

**Comment by michalmuskala** [comment]
We have `change_map` and `change_array` now: https://github.com/michalmuskala/mongodb_ecto/commit/2a0a4cb3d09b7c50ff829d7b419565812b642293
