### ISSUE TITLE
Update Phoenix generator to support Ecto+Mongo out of the box

### ISSUE THREAD

**Issue by josevalim** [michalmuskala/mongodb_ecto#31]

**Comment by michalmuskala** [comment]
I think we need to release a hex package first so there is no problem with versions.

**Comment by michalmuskala** [comment]
I was looking into this and it seems this will require quite a lot of changes to the `phoenix.new` generator:
  * We need a different `config/test.exs` file (no `Ecto.Adapters.SQL.Sandbox`), 
  * change test helpers to use `Mongo.truncate/1` in stead of `Ecto.Adapters.SQL.restart_test_transaction/1`
  * change `Web.model` to override default `@primary_key`.
There may be other things.
