### ISSUE TITLE
Publish to Hex

### ISSUE THREAD

**Issue by optikfluffel** [michalmuskala/mongodb_ecto#37]
This would be pretty cool. They also have [a nice guide for it](https://hex.pm/docs/publish).

**Comment by michalmuskala** [comment]
Thank you for suggestion. This is actually the plan, but we need all our dependencies to be published on hex too. Hopefully this will happen soon.

**Comment by optikfluffel** [comment]
I opened an issue for `:mongodb` (ericmj/mongodb#17), that should be the last one as far as I can see.

**Comment by optikfluffel** [comment]
[ericmj/mongodb](https://github.com/ericmj/mongodb) is [published to hex now](https://hex.pm/packages/mongodb) :grin:

**Comment by michalmuskala** [comment]
I'm working on this right now :smile:

**Comment by optikfluffel** [comment]
![Yay!](http://www.reactiongifs.com/r/pnda.gif)

**Comment by michalmuskala** [comment]
:tada: https://hex.pm/packages/mongodb_ecto :tada:

**Comment by williamgueiros** [comment]
\o/
