### ISSUE TITLE
Unselecting fields

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#4]
When making a projection (selecting document parts we want) we can either select what fields we want - that's what I do currently with select clauses. But there is also possibility to unselect certain fields - to request all fields except that one. Both cannot be combined. It's related to the #3.
How should we go about this? Something similar to select? I know we shouldn't add another field to the Query struct. Maybe then some kind of a modifier? I was thinking about something similar to this:
```elixir
from u in User
     select: not u.name
```

**Comment by ericmj** [comment]
I don't think this should be supported in ecto since a model is a possible subset of a table or document.

**Comment by josevalim** [comment]
@ericmj it would still make sense because you can say "give me everything except this" for this model. 

Maybe one way to support this would be with the update syntax:

    select: %{p | name: nil}

We know the name is being set to nil, so we know we don't need to bring it from the database.

However, I think can safely skip this feature until somebody asks for it. It seems low priority compared to everything else we have.

**Comment by ericmj** [comment]
@josevalim That means we will be selecting potential fields that are not on the model (something we do not do for SQL). We can support the same behaviour by just selecting one less field.

**Comment by josevalim** [comment]
@ericmj I am not sure I follow? The query above should get all fields in the model, except name.

**Comment by ericmj** [comment]
@josevalim But it doesn't have to use the unselect syntax from mongo, we can use the usual select syntax and just don't select that field (we can do the same thing for SQL adapters).

**Comment by josevalim** [comment]
@ericmj that sucks because if you want all fields, except one, it is tons of work. For example, imagine some field contains an embedded association you **know** it is large. You want everything, except it.

**Comment by michalmuskala** [comment]
There is no way to do this in Ecto currently so I'm closing this.
