### ISSUE TITLE
Question: Adding indexes

### ISSUE THREAD

**Issue by vitalis** [michalmuskala/mongodb_ecto#42]
Hi,
I don't see any docs on adding indexes, can you please help?

**Comment by michalmuskala** [comment]
I think the most straightforward way would be to do this from mongo console.

That being said, we support using Ecto's migrations for adding indexes - it should work like with any other database (having in mind that other migration options like creating tables make no sense for MongoDB). You can find more documentation on this here: https://hexdocs.pm/ecto/Ecto.Migration.html#index/3

If you'll still have some problems or you encounter some issues, please report back :smiley:

**Comment by vitalis** [comment]
@michalmuskala thank you very much!

**Comment by michalmuskala** [comment]
@vitalis I've updated the documentation on migrations and indexing. https://github.com/michalmuskala/mongodb_ecto/commit/b4152efc92b70a510df6a7c5c6261099e6e29795
Do you think it's more helpful now?

**Comment by vitalis** [comment]
@michalmuskala the docs update looks very good!
