### ISSUE TITLE
Mapping of symbol?

### ISSUE THREAD

**Issue by johnnyshields** [michalmuskala/mongodb_ecto#44]
In the Data Types in the doc, it says

```
symbol              ???
```

What does this mean?

**Comment by michalmuskala** [comment]
Thank you for noticing this. There was no support for symbols in the driver when I wrote this, but this has changed since. I updated the documentation to mark symbols as unsupported and deprecated:

> Symbols are deprecated by the BSON specification. They will be converted to simple strings on reads. There is no possibility of persisting them to the database.
