### ISSUE TITLE
Timeout on queries.

### ISSUE THREAD

**Issue by fcruxen** [michalmuskala/mongodb_ecto#49]
The problem is described here: 
https://gist.github.com/fcruxen/9ad456039eee91632cd8

José Valim in the google groups topics suggested using the timeout attribute when configuring the Repo, same thing, queries still fail after 5000ms.

Increasing pool size had no effect on this too.

Thanks in advance,
Felipe Cruxen

**Comment by michalmuskala** [comment]
I looked at the adapter itself and the driver, and it seems in both places we handle timeouts quite poorly. I think the main reason is there are multiple different timeouts:
  * queue timeout
  * query timeout (for a single call to Mongo - there can be multiple with coursors)
  * internal Mongo timeout `$maxTimeMS`
  * the overall timeout as seen by the user

It looks like currently the `timeout` option is only used for the tcp connection with the database.

I'm thinking about which ones we should configure and how.
\cc @ericmj

**Comment by fcruxen** [comment]
Thanks for the response. Ok, while you guys bake this, I'll fork the lib and change manually the values.

**Comment by fcruxen** [comment]
@michalmuskala |> sorry to bother again, I've increased the query timeout to 60 seconds. The number of errors decreased dramatically, but I am still getting timeout errors as described in the first post. I've tried  increasing the number of containers, to share the load, but it had no effect. Increasing/decreasing the pool size had no effect either. Any tip of what this may be? Thanks in advance.

**Comment by kwojtaszek** [comment]
@fcruxen do you have all hosts in replicaset setup properly? It's well known issue in ruby environment, maybe it apply to your coase too: https://github.com/mongoid/moped/issues/257

**Comment by fcruxen** [comment]
Yes, They are all correct.

I’ve patched the driver to some hardcoded values for query timeout and connection timeout.

The issue was due to connection limits in the container env. I’ve corrected the issue in the env, instead of just decreasing the pool limit. I’ll try to make some other tests and if brave enough a PR to better control those timeouts.

Thanks a lot for all the attention and help.


-- 

Sent with Airmail

On 25 de dezembro de 2015 at 09:49:35, Karol Wojtaszek (notifications@github.com) wrote:

@fcruxen do you have all hosts in replicaset setup properly? It's well known issue in ruby environment, maybe it apply to your coase too: mongoid/moped#257

**Comment by ericmj** [comment]
A PR would be greatly appreciated.
