### ISSUE TITLE
MongoDB operator support

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#5]
This is a list of MongoDB operators. I don't think it would be reasonable to support all of those, especially the more exotic ones like the $geoWithin. An approach similar to SQL's fragments could probably work here quite well. The ones that are marked are used somewhere as of now.

#### Comparison
- [ ] $eq - Matches values that are equal to a specified value.
- [x] $gt - Matches values that are greater than a specified value.
- [x] $gte - Matches values that are greater than or equal to a specified value.
- [x] $lt - Matches values that are less than a specified value.
- [x] $lte - Matches values that are less than or equal to a specified value.
- [x] $ne - Matches all values that are not equal to a specified value.
- [x] $in - Matches any of the values specified in an array.
- [x] $nin - Matches none of the values specified in an array.

#### Logical
- [x] $or - Joins query clauses with a logical OR returns all documents that match the conditions of either clause.
- [x] $and - Joins query clauses with a logical AND returns all documents that match the conditions of both clauses.
- [x] $not - Inverts the effect of a query expression and returns documents that do not match the query expression.
- [ ] $nor - Joins query clauses with a logical NOR returns all documents that fail to match both clauses.

There are special cases for `not value in array` to use $nin operator, and for `not is_nil(value)` to use $neq with null.

#### Element
- [ ] $exists - Matches documents that have the specified field.
- [ ] $type - Selects documents if a field is of the specified type.

#### Evaluation
- [ ] $mod - Performs a modulo operation on the value of a field and selects documents with a specified result.
- [ ] $regex - Selects documents where values match a specified regular expression.
- [ ] $text - Performs text search.
- [ ] $where - Matches documents that satisfy a JavaScript expression.

#### Geospatial
- [ ] $geoWithin - Selects geometries within a bounding GeoJSON geometry. The 2dsphere and 2d indexes support $geoWithin.
- [ ] $geoIntersects - Selects geometries that intersect with a GeoJSON geometry. The 2dsphere index supports $geoIntersects.
- [ ] $near - Returns geospatial objects in proximity to a point. Requires a geospatial index. The 2dsphere and 2d indexes support $near.
- [ ] $nearSphere - Returns geospatial objects in proximity to a point on a sphere. Requires a geospatial index. The 2dsphere and 2d indexes support $nearSphere.

#### Array
- [ ] $all - Matches arrays that contain all elements specified in the query.
- [ ] $elemMatch - Selects documents if element in the array field matches all the specified $elemMatch conditions.
- [ ] $size - Selects documents if the array field is a specified size.

#### Projection Operators
- [ ] $ - Projects the first element in an array that matches the query condition.
- [ ] $elemMatch - Projects the first element in an array that matches the specified $elemMatch condition.
- [ ] $meta - Projects the document’s score assigned during $text operation.
- [ ] $slice - Limits the number of elements projected from an array. Supports skip and limit slices.

---
#### Fields
- [ ] $inc - Increments the value of the field by the specified amount.
- [ ] $mul - Multiplies the value of the field by the specified amount.
- [ ] $rename - Renames a field.
- [ ] $setOnInsert - Sets the value of a field if an update results in an insert of a document. Has no effect on update operations that modify existing documents.
- [ ] $set - Sets the value of a field in a document.
- [ ] $unset - Removes the specified field from a document.
- [ ] $min - Only updates the field if the specified value is less than the existing field value.
- [ ] $max - Only updates the field if the specified value is greater than the existing field value.
- [ ] $currentDate - Sets the value of a field to current date, either as a Date or a Timestamp.

##### Operators
- [ ] $ - Acts as a placeholder to update the first element that matches the query condition in an update.
- [ ] $addToSet	 - Adds elements to an array only if they do not already exist in the set.
- [ ] $pop - Removes the first or last item of an array.
- [ ] $pullAll - Removes all matching values from an array.
- [ ] $pull - Removes all array elements that match a specified query.
- [ ] $pushAll - Deprecated. Adds several items to an array.
- [ ] $push - Adds an item to an array.

##### Modifiers
- [ ] $each - Modifies the $push and $addToSet operators to append multiple items for array updates.
- [ ] $slice - Modifies the $push operator to limit the size of updated arrays.
- [ ] $sort - Modifies the $push operator to reorder documents stored in an array.
- [ ] $position - Modifies the $push operator to specify the position in the array to add elements.

#### Bitwise
- [ ] $bit - Performs bitwise AND, OR, and XOR updates of integer values.

#### Isolation
- [ ] $isolated - Modifies the behavior of a write operation to increase the isolation of the operation.

---
#### Modifiers
- [ ] $comment - Adds a comment to the query to identify queries in the database profiler output.
- [ ] $explain - Forces MongoDB to report on query execution plans.
- [ ] $hint - Forces MongoDB to use a specific index. 
- [ ] $maxScan - Limits the number of documents scanned.
- [ ] $maxTimeMS - Specifies a cumulative time limit in milliseconds for processing operations on a cursor.
- [ ] $max - Specifies an exclusive upper limit for the index to use in a query.
- [ ] $min - Specifies an inclusive lower limit for the index to use in a query. 
- [x] $orderby - Returns a cursor with documents sorted according to a sort specification.
- [ ] $returnKey - Forces the cursor to only return fields included in the index.
- [ ] $showDiskLoc - Modifies the documents returned to include references to the on-disk location of each document.
- [ ] $snapshot - Forces the query to use the index on the _id field.
- [x] $query - Wraps a query document.

The $query and $orderby operators are used to implement order_by clauses.

#### Sort Order
- [ ] $natural - A special sort order that orders documents using the order of documents on disk.

---
### [Aggregation Pipeline Operators](http://docs.mongodb.org/manual/reference/operator/aggregation/)

These allow for some really advanced queries, basically a mapReduce but without javascript. Using these it would be possible to simulate group_by or having SQL clauses. I won't list them, as I think they are way beyond the current scope.

**Comment by josevalim** [comment]
I think we don't  have much option here besides supporting some sort of `fragment` syntax for mongo too. Maybe `fragment(keyword | map)`?

**Comment by ericmj** [comment]
:+1: to `fragment(map)`.

**Comment by josevalim** [comment]
Fragment it is. We can start focusing on those new features after we get a passing test suite. :)

**Comment by michalmuskala** [comment]
I think we can close this, as we support fragments.

**Comment by PotterDai** [comment]
will we have features for the Array operators? Like put, pull, etc.

**Comment by michalmuskala** [comment]
Those are available directly with `update_all` http://hexdocs.pm/ecto/Ecto.Query.html#update/3
