### ISSUE TITLE
`:slave_ok` option for reads - any example in action?

### ISSUE THREAD

**Issue by amokan** [michalmuskala/mongodb_ecto#50]
I'm curious if anyone has an example of how to pass the `:slave_ok` option for queries mentioned in the source?

I've tried variations on `MyRepo.one(query, {:slave_ok})` with no luck. I'm sure I'm just missing something simple.

Even better would be this ability to just force all queries to use this option. Maybe during the connection config or something?

Thanks. I really appreciate any help.

**Comment by amokan** [comment]
I may have solved my problem, but need to verify it is behaving how I expect against a real replica set

`MyRepo.one(query, opts: [:slave_ok])`

Still would be handy to just be able to have this behavior be the default at setup when warranted, though. If anyone has any insight on making that work, I would appreciate it. Thanks!

**Comment by michalmuskala** [comment]
The proper way to pass this option is with:
```elixir
MyRepo.one(query, slave_ok: true)
```

You can add additional function in your repo, that would have this as a default:
```elixir
def one_slave_ok(query, opts \\ []) do
  opts = Keyword.put_new(opts, :slave_ok, true)
  one(query, opts)
end
```
Then instead of calling `MyRepo.one/2` you'd call `MyRepo.one_slave_ok/2`

How this option will be handled, I have to admit, I'm not sure. Maybe @ericmj will have more knowledge about how `:slave_ok` is handled in the driver.

**Comment by ericmj** [comment]
This option doesn't do anything right now because replica sets are not supported yet.

**Comment by ericmj** [comment]
Sorry, the option is actually used if you connect via `mongos` instances.

**Comment by amokan** [comment]
@ericmj @michalmuskala Yeah, I can see it is not working right now when connected to a `mongod` replica set. This is fine for my current scenario where I am trying to get through some data as fast as possible to fix a problem (and thank you all __so much__ for the work on this project, because this and Elixir have saved me a ton of time in the past 12 hours that would have been a nightmare in Ruby). Having said that, it would be great to eventually have the ability to connect to a non `mongos` replica set if I ever wanted to switch from Rails to Phoenix on this particular system, which I would like to do someday.

Maybe I'm in a weird scenario - but we do not use mongo sharding for various reasons. Just replica sets with many servers. We perform nearly all reads against the slaves and certain portions of the system use specific slaves. We currently use Mongoid ruby for our driver and it supports this scenario well. I will have to look into their connection process to see how they handle things. I will mention that verbosely specify an array of the servers for our Mongoid driver rather than let the master tell us which slaves are available and handle it magically. I suppose I could make another repo pointed at a slave or two and just use that repo for certain reads.

**Comment by ericmj** [comment]
Replica sets are definitely on the roadmap.

**Comment by amokan** [comment]
@ericmj i just noticed that on your driver repo. excellent news. thanks for your help!

**Comment by michalmuskala** [comment]
Given we can't do anything in the adapter until there's support for this in the driver I will close this issue for now.
