### ISSUE TITLE
array type containing nil values

### ISSUE THREAD

**Issue by amokan** [michalmuskala/mongodb_ecto#51]
I have a model that goes something like this (_obviously contrived_) and I'm connecting to a legacy database. I'm having some issues with the `{:array, subtype}` field, though

```
defmodule Foo do
  schema "foo" do
    field :some_val, :integer
    field :value_history, {:array, :integer}, default: []
  end
end
```

Everything is working perfectly fine on reads, but when I create a new instance of the model and try to assign the `value_history` attribute - it will explode if I have any values in the array/list that are nil when I try to insert. I get this, because I said the subtype is integer - but I'm really hoping there is another way to handle this.

__fails upon insert__
```
foo = %Foo{some_val: 5, value_history: [5, 1, 2, nil, 6, 2, 2]}
```

__works fine upon insert__
```
foo = %Foo{some_val: 5, value_history: [5, 1, 2, 6, 2, 2]}
```

Is there a way to opt out of the type-check here or at least say, _"the array subtype is integer and nil is allowed"_?

Unfortunately I have two years of mongo docs across three massive replica sets (20+ servers total) that follow this paradigm, so I'm really hoping for a clean work around.

**Comment by amokan** [comment]
Looks like `{:array, :any}` works for the type declaration. Anything I'm losing other than just no validation that the subtypes are actually integers?

**Comment by michalmuskala** [comment]
You also loose type casting - normally when using `Changeset.cast/4` string representation of integers are also converted to integers. This may be fine depending on how you use it.

**Comment by amokan** [comment]
@michalmuskala yeah. seems fine for my situation, but I will keep that in mind. Thank you.

**Comment by josevalim** [comment]
@michalmuskala is this an ecto bug? should we allow nils in lists by default or not really?

**Comment by michalmuskala** [comment]
After giving it some though I think we should support this.
You can have `NULLS` in postgres in arrays so it may make sense to accept those in Ecto too. One way to get them is that you can set a particular element to enlarge your array (e.g. tenth when you have only 2 values) - the missing fields will be filled with `NULL`s.
I'll open an issue on ecto.
