### ISSUE TITLE
Error connecting to remote database

### ISSUE THREAD

**Issue by AdamBrodzinski** [michalmuskala/mongodb_ecto#52]
I spun up a temp. test db on Compose.io and am having issues connecting. I can connect with the shell but I must be messing up the config somehow? It's also a replica set so I used the same hostname that the shell used. It wasn't clear how the mongo URI should be used in the config.

I can’t figure out why it’s crashing… Any tips? It works great with a local mongo. I can login using the shell:
`mongo candidate.16.mongolayer.com:11213/chatty -u testu -p testp`

```elixir

config :chatty, Chatty.Repo,
  database: "chatty",
  username: "testu",
  password: "testp",
  #hostname: "candidate.16.mongolayer.com:11213,candidate.57.mongolayer.com"
  hostname: "candidate.16.mongolayer.com",
  port: "11213"
```

and the error on startup:

```
State: %{auth: [{"testu", "testp"}], database: "chatty", opts: [backoff: 1000, pool_name: Chatty.Repo.Pool, pool: Ecto.Pools.Poolboy, otp_app: :chatty, repo: Chatty.Repo, hostname: 'candidate.16.mongolayer.com', port: "11213"], queue: %{}, request_id: 0, socket: nil, tail: nil, timeout: 5000, wire_version: nil, write_concern: [w: 1]}
[error] GenServer #PID<0.1716.0> terminating
** (stop) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :inet_tcp.getserv/1
        (kernel) inet_tcp.erl:36: :inet_tcp.getserv("11213")
        (kernel) gen_tcp.erl:157: :gen_tcp.connect1/4
        (kernel) gen_tcp.erl:144: :gen_tcp.connect/4
        (mongodb) lib/mongo/connection.ex:187: Mongo.Connection.connect/2
        (connection) lib/connection.ex:608: Connection.enter_connect/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (kernel) gen_tcp.erl:149: :gen_tcp.connect/4
    (mongodb) lib/mongo/connection.ex:187: Mongo.Connection.connect/2
    (connection) lib/connection.ex:608: Connection.enter_connect/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

The URI compose gives me is:  
```
mongodb://<user>:<password>@candidate.16.mongolayer.com:11213,candidate.57.mongolayer.com:10138/chatty?replicaSet=set-56489fdcbab49bb86e000bfb
```

**Comment by AdamBrodzinski** [comment]
Ah got it after reading through the source code (this always happens right after I post lol). I just used a `url` key in the config and that was accepted. Would you accept a PR to add this to the docs?

**Comment by mdgart** [comment]
Same issue here, this should be documented somewhere

**Comment by michalmuskala** [comment]
Do you mean providing both `username`, `hostname`, etc and `url`? 
If so this is an issue of ecto itself, and we could definitely give a better error message.

**Comment by mdgart** [comment]
I don't see any other way to specify the port, it's not in the documentation at all or at least I did not find it. Also a better error message would be great.

**Comment by AdamBrodzinski** [comment]
@michalmuskala after re-visiting this for a while, I think my inexperience with both Ecto and Phoenix were at fault. At the time I thought that perhaps I had to split apart the mongo url string and put it into the config map.... however, I just needed to change:

```
config :chatty, Chatty.Repo,
  database: "chatty",
  username: "testu",
  password: "testp",
  hostname: "candidate.16.mongolayer.com",
  port: "11213"
```

to

```
config :chatty, Chatty.Repo,
  # fake url
  url: "mongodb:/testu:testp@candidate.99.mongolayer.com:11212,candidate.57.mongolayer.com:10138/chatty?replicaSet=set-99989fdcbab49bb86e000bfb
"
```

I guess the part we were both confused about it that the config keys are not well documented anywhere. I'm assuming http://hexdocs.pm/ecto/Ecto.html under the `config/config.exs` section would be a good place for it. 

Not exactly sure how to phase it in the readme as you would typically  use one or the other. Here's a rough cut:

> Where the configuration for the Repo must be in your application environment, usually defined in your `config/config.exs`:

```elixir
config :my_app, Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "ecto_simple",
  username: "postgres",
  password: "postgres",
  hostname: "localhost"
  # or an optional URL
  url: "postgres://username@localhost/ecto_simple"
```

**Comment by ericmj** [comment]
Also note that the driver doesn't support replica sets.

**Comment by emerleite** [comment]
Any news on this, folks? ecto mongo does not support replica?

**Comment by Morganjackson** [comment]
@AdamBrodzinski Are you still using this? I have tried the config map and setting the url which both work   for 5 - 10 minutes before I get a timeout error.

[error] #PID<0.401.0> running Demo.Endpoint terminated
Server: johndoe.localhost:4000 (http)
Request: GET /
** (exit) exited in: GenServer.call(#PID<0.334.0>, {:find, "users", [{"$query", [username: "johndoe"]}, {"$orderby", %{}}], %{_id: true}, [batch_size: 1000]}, 5000)
    ** (EXIT) time out
[error] Mongo tcp error (galaga.3.mongolayer.com:10161): connection timed out
[error] Mongo tcp error (galaga.3.mongolayer.com:10161): closed

**Comment by AdamBrodzinski** [comment]
@Morganjackson not anymore, i switched over to using RethinkDB and the Elixir driver
