### ISSUE TITLE
Object ids inside ecto type :map are incorrectly decoded

### ISSUE THREAD

**Issue by ericmj** [michalmuskala/mongodb_ecto#54]
They are currently decoded as binaries: https://github.com/michalmuskala/mongodb_ecto/blob/cde237fd347ed5e1c8570f4b6a7be26e1698fef5/lib/mongo_ecto/decoder.ex#L27-L28.

It seems like all these decodings are incorrect if we don't have a schema type, because we don't know how to encode them later when we are going to persist them. For example a `BSON.Binary` decoded to a simple binary https://github.com/michalmuskala/mongodb_ecto/blob/cde237fd347ed5e1c8570f4b6a7be26e1698fef5/lib/mongo_ecto/decoder.ex#L25-L26. But when encoding it is not encoded back to a `BSON.Binary` https://github.com/michalmuskala/mongodb_ecto/blob/cde237fd347ed5e1c8570f4b6a7be26e1698fef5/lib/mongo_ecto/encoder.ex#L30-L31.

/cc @michalmuskala @josevalim

**Comment by michalmuskala** [comment]
Closed via https://github.com/michalmuskala/mongodb_ecto/pull/58
