### ISSUE TITLE
Schema timestamps macro doesn't appear to be handled properly

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#62]
I have a very basic MongoDB schema structure, with model (document) "A" having an embeds_many relationship with model (document) "B". Both A and B specify the timestamps macro in their schema definitions. When I insert a new A containing several children B, here's what is persisted to MongoDB: 

1. Collection A is created, with no timestamp fields at all. 
2. The several B children are created within A as expected, and while these are created with inserted_at and updated_at fields, these fields are not properly populated, they are both NULL. 

There appear to be two problems: 
1. Top level schemas don't appear to persist timestamp fields at all. 
2. Embedded schemas appear to persist, but do not populate, timestamp fields. 

If read through ecto documentation which has compatibility with mongodb_ecto (most recent version is ecto 1.0.7) and it would appear that this should be supported in mongodb_ecto.

**Comment by brado** [comment]
I originally tested this against MongoDB version 3.2. I now can confirm that this is also an issue in MongoDB version 2.6.11.

**Comment by rafal-radziszewski** [comment]
Just wanted to say that we use timestamps and it works properly from beginning on Mongodb 3.2.

**Comment by brado** [comment]
....but mongo_ecto doesn't support MongoDB 3.2 yet (AFAIK, it didn't as of a few weeks ago). I was actually on MongoDB 3.2, but had to move back to 2.x because truncate wasn't supported and it crashed all of my unit tests.

**Comment by rafal-radziszewski** [comment]
I don't know about truncate, but timestamps and general db operations are just fine, we use it on staging. I'm not saying it's fully supported, but no major hickups so far. The only problem we have is replicasets, but it's version independent and there is a workaround.

**Comment by brado** [comment]
In my Phoenix web apps (I have several) I am using: 

mongodb_ecto 0.1.4
ecto 1.0.7
phoenix_ecto 1.2.0

because this is the newest version of all three which to my knowledge work together. I ran into problems using phoenix_ecto 2.0 with mongo_ecto. If anyone knows of newer versions of the three libraries above which have no incompatibilities with one another, by all means, please let me know. 

That said, to date, I never have seen timestamps work at all with any 2.x or 3.x version of MongoDB (I'm using 3.2.4 now). Specifically:

1. Neither inserted_at nor updated_at fields appear at all in any parent (top-level) MongoDB document inserted for any Phoenix model.
2. The inserted_at and updated_at fields do appear in MongoDB embedded child documents (models) but their values are always NULL. 

Now, I'm not sure if these had to be added to the @required_fields or @optional_fields lists in the model in order to be persisted properly, but if that is supposed to be the case, I'd point out two things: 

- The model files generated with phoenix.gen.html and phoenix.gen.json automatically declare timestamps, but do not include timestamps in either @required_fields or @optional_fields lists, so if those are supposed to be there, that should probably be considered a bug. 
- It seems very strange that inserted_at and updated_at fields appear in embedded models, but not in the parent. What's the difference? 

At any rate, if anyone could lend some guidance as to whether timestamps are just outright broken, or whether there's something you have to do to get them to work, I'd greatly appreciate it. 

Thanks...

**Comment by brado** [comment]
One additional note....you can't include timestamps in the @required_fields or @optional_fields lists -- it is illegal -- I just tested it. So that isn't a viable approach -- if someone can lend guidance for how to get these to work, that would be great. 

Thanks.

**Comment by michalmuskala** [comment]
This indeed seems very strange. I will investigate.

**Comment by brado** [comment]
Thanks @michalmuskala. If there is anything more I can do or info I can provide to help, let me know.

What I am doing is so vanilla, I'm not sure where to start to debug it further. Create a model using `mix phoenix.gen.json` and persist to MongoDB, and there you go. If it works anywhere else, I'm wondering if this is an issue of dependency versions or incompatibilities somehow, because I would guess it should normally work right out of the box. That's one reason I mentioned the versions of ecto, phoenix_ecto, and mongodb_ecto above, because that was my biggest challenge in integrating mongodb_ecto, finding the versions of libraries which actually worked with one another, because it appears a fair gap has opened between ecto / phoenix_ecto current versions and what mongodb_ecto supports. 

Listing the versions of all three that are considered current relative to this project in the README might be a big help...it would help project configuration right out of the gate -- because the default `mix phoenix.new` creates a project that is not compatible with the current version of mongodb_ecto.

**Comment by michalmuskala** [comment]
@brado I tested this and it definitely seems to work correctly. Can you check the changeset just before handing it to the `Repo`? Does it have values for timestamps in the `changes` part? If so ecto won't insert  new values and use those you - the user - inserted.

The relevant test is here: https://github.com/michalmuskala/mongodb_ecto/commit/80c3a191d57e2fd2ed583ca886b0c2973ba9da8e

**Comment by brado** [comment]
Here's what I do to reproduce this issue:

- Created a new Phoenix web app project using: `mix phoenix.new bigdog --database mongodb`
- Changed dependencies in mix.exs to: 

```
    #  {:mongodb_ecto, ">= 0.0.0"},
     {:mongodb_ecto, "~> 0.1.4"},
     # {:phoenix_ecto, "~> 2.0"},
     {:phoenix_ecto, "~> 1.2"},
```
- Generated a new JSON API using `mix phoenix.gen.json API.Car cars  make:string model:string year:integer`

I made no other code changes, other than to make the id an optional field. here is the generated model definition with that minor change: 

```
defmodule Bigdog.API.Car do
  use Bigdog.Web, :model

  schema "cars" do
    field :make, :string
    field :model, :string
    field :year, :integer

    timestamps
  end

  @required_fields ~w(make model year)
  @optional_fields ~w(id)

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```

Without making any code changes, I tried to insert a JSON doc as an HTTP POST. Here is the Phoenix console output, showing first the parameters received by the controller, second an `IO.inspect changset` on the create changeset, and finally the MongoDB operation: 

```
[info] POST /api/cars

[debug] Processing by Bigdog.API.CarController.create/2
  Parameters: %{"car" => %{"id" => "5759f1d610e3a41a0b6c78de", "make" => "Honda", "model" => "Pilot", "year" => 2016}}
  Pipelines: [:api]

%Ecto.Changeset{action: nil,
 changes: %{id: "5759f1d610e3a41a0b6c78de", make: "Honda", model: "Pilot",
   year: 2016}, constraints: [], errors: [], filters: %{},
 model: %Bigdog.API.Car{__meta__: #Ecto.Schema.Metadata<:built>, id: nil,
  inserted_at: nil, make: nil, model: nil, updated_at: nil, year: nil},
 optional: [:id], opts: [],
 params: %{"id" => "5759f1d610e3a41a0b6c78de", "make" => "Honda",
   "model" => "Pilot", "year" => 2016}, repo: nil,
 required: [:make, :model, :year],
 types: %{id: :binary_id, inserted_at: Ecto.DateTime, make: :string,
   model: :string, updated_at: Ecto.DateTime, year: :integer}, valid?: true,
 validations: []}

[debug] INSERT coll="cars" document=[_id: #BSON.ObjectId<5759f1d610e3a41a0b6c78de>, make: "Honda", model: "Pilot", year: 2016] [] OK query=0.4ms
[info] Sent 201 in 99ms
```

Here is the document that results in MongoDB 3.2.4: 

```
{
  "_id": ObjectId("5759f1d610e3a41a0b6c78de"),
  "make": "Honda",
  "model": "Pilot",
  "year": 2016
}
```

Ideas? Maybe I have assumed wrong, but I have thought that timestamps were supposed to work out of the box with generated code. Is there something I'm supposed to do to get it to work? Please advise....I'm hoping this is something easy I've overlooked....I've been creating Phoenix web app projects and generating models and I have never seen this work. 

Thanks....

**Comment by michalmuskala** [comment]
The issue stems from the fact that you use one of the newer phoenix generators that targets new versions of ecto, and produces some incompatibilities.

The one that you face in here is the fact that ecto switched from `use Ecto.Model` in 1.0 to `use Ecto.Schema` in the next versions. The main difference, that is relevant here, is the fact that schema does not include callbacks - and callbacks were used in 1.0 to fill timestamps.

To solve this you can change `use Ecto.Schema` to `use Ecto.Model` in `web/web.ex`.

**Comment by brado** [comment]
Yep....that did it. I guess it is a wait until mongodb_ecto for Ecto 2.0 before using Ecto.Schema. It might be good to put some doc in the readme that mongodb_ecto doesn't presently won't work with a vanilla Phoenix project created with `mix phoenix.new` for the current version of Phoenix. Both mix.exs dependencies and this Ecto.Schema to Ecto.Model in web.ex need to be changed. 

Thanks for your help @michalmuskala.
