### ISSUE TITLE
mix phoenix.gen.html controller test fails on id input

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#67]
I have controller tests were generated as part of executing the following command:
```
mix phoenix.gen.html
```
This creates a number of files, of course, one being a controller and controller test. When running these tests without any alteration, I received several errors, one of which was the following:
```
$ mix test test/controllers/car_controller_test.exs 
test/controllers/car_controller_test.exs:4: warning: unused alias Car

  1) test renders page not found when id is nonexistent (Shrek.CarControllerTest)
     test/controllers/car_controller_test.exs:40
     expected response status to be 404, but got 500 from:
     
     ** (FunctionClauseError) no function clause matching in Mongo.Ecto.ObjectID.dump/1
     
     stacktrace:
       (mongodb_ecto) lib/mongo_ecto/objectid.ex:25: Mongo.Ecto.ObjectID.dump("11111111-1111-1111-1111-111111111111")
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (ecto) lib/ecto/repo/queryable.ex:91: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:55: Ecto.Repo.Queryable.one!/4
       (shrek) web/controllers/car_controller.ex:32: Shrek.CarController.show/2
       (shrek) web/controllers/car_controller.ex:1: Shrek.CarController.action/2
       (shrek) web/controllers/car_controller.ex:1: Shrek.CarController.phoenix_controller_pipeline/2
       (shrek) lib/phoenix/router.ex:261: Shrek.Router.dispatch/2
       (shrek) web/router.ex:1: Shrek.Router.do_call/2
```
Here's the source code of this test:
```
  test "renders page not found when id is nonexistent", %{conn: conn} do
    assert_error_sent 404, fn ->
      get conn, car_path(conn, :show, "11111111-1111-1111-1111-111111111111")
    end
  end
```
It would appear that the test is choking on the string input, and the structure of the object ID. I'm not sure what would be the conclusion here, whether there is a bug in the generator, or in the declaration of the model. Here is the model (with the @primary_key added):
```
defmodule Shrek.Car do
  use Shrek.Web, :model

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "cars" do
    field :year, :integer
    field :make, :string
    field :model, :string

    timestamps
  end

  @required_fields ~w(year make model)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```
If anyone can help me get past this error, that would be great. I'm not exactly sure what the root nature of the problem is, but given that the generated model / test are failing, it is a bug of some kind. I'm sure the resolution in the interim is probably to change the input value, so if someone can help me rectify this, I would be greatly appreciative. Thanks.

**Comment by michalmuskala** [comment]
Fixed in https://github.com/phoenixframework/phoenix/pull/1469

**Comment by brado** [comment]
@michalmuskala  I'm not seeing any change of behavior on the phoenix master or v1.1.3 per the issue mentioned above. I'm getting the exact same test error on controller tests generated using mix phoenix.gen.html as before using the master. The pull request referenced seems to change the output of the generator to include test data for binary ID's of "11111111-1111-1111-1111-111111111111". That seems to work fine, as I see that sample data in my controller tests. But the problem is in the handling of it. I receive this error when I run the test:
```
 1) test renders page not found when id is nonexistent (Shrek.CarControllerTest)
     test/controllers/car_controller_test.exs:35
     expected response status to be 404, but got 500 from:

     ** (FunctionClauseError) no function clause matching in Mongo.Ecto.ObjectID.dump/1

     stacktrace:
       (mongodb_ecto) lib/mongo_ecto/objectid.ex:25: Mongo.Ecto.ObjectID.dump("11111111-1111-1111-1111-111111111111")
       (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (ecto) lib/ecto/repo/queryable.ex:91: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
       (ecto) lib/ecto/repo/queryable.ex:55: Ecto.Repo.Queryable.one!/4
       (shrek) web/controllers/car_controller.ex:32: Shrek.CarController.show/2
       (shrek) web/controllers/car_controller.ex:1: Shrek.CarController.action/2
       (shrek) web/controllers/car_controller.ex:1: Shrek.CarController.phoenix_controller_pipeline/2
       (shrek) lib/phoenix/router.ex:261: Shrek.Router.dispatch/2
       (shrek) web/router.ex:1: Shrek.Router.do_call/2
```
If you have any insight into this and can advise, I'd appreciate it. Thx.

**Comment by michalmuskala** [comment]
Ah, you're right. The fix in phoenix was for generating a UUID, but here we need an ObjectId. Unfortunately it's not easily possible to know what is needed when the generator is running because we don't have access to the Ecto adapter. Only the adapter knows the format of `binary_id`.

**Comment by brado** [comment]
@michalmuskala I thought I was going crazy...relieved to know what I'm seeing is legit. I'm fine with making a manual fix to get my tests working. I'm guessing changing the test data will rectify the test for the interim: 
```
test "renders page not found when id is nonexistent", %{conn: conn} do
    assert_error_sent 404, fn ->
      get conn, car_path(conn, :show, "11111111-1111-1111-1111-111111111111")
    end
  end
```
What is an acceptable value for the ID or test rewrite that will work? 

Second question -- in live usage, that string ID will be incoming off the URL -- shouldn't it be able to handle an invalid ID string of any format, and return a 404 error? I'm a little unclear why we shouldn't be able to send in an ID of "this_is_a_junk_id" without it blowing up. What happens if a junk ID comes in off a URL?

**Comment by brado** [comment]
I can confirm that changing this line in the aforementioned test: 
```
get conn, car_path(conn, :show, "11111111-1111-1111-1111-111111111111")
```
to this: 
```
      get conn, port_path(conn, :show, "56a537b63e0eee155869a051")
```
succeeds. Still shouldn't have to do that though. I think this issue ought to be reopened, here, or in phoenix, or both.
