### ISSUE TITLE
Bulk insert?

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#70]
Is it possible to accomplish a bulk insert (insert of many documents into a collection in one insert operation)? If so, how is this done, and if not, as MongoDB supports it, what is the prospect of adding this to mongodb_ecto? 

I'm guessing that this may be a problem that pins back to ecto, but this would be nice if possible.

**Comment by michalmuskala** [comment]
Ecto 2.0 will come with a `insert_all` function. For now you could use `Mongo` APIs directly, in particular `Mongo.insert_many/4`. You need to pass plain maps only to it (not Ecto structs) and no special Ecto type-dumping will happen (it will probably be most painful with datetimes), but it should work. You can access your Repo's underlying pool (that you need to use with `Mongo` functions) with `Repo.__mongo_pool__/0`

```elixir
documents = [%{field: "value"}, %{field: "other_value"}]
Mongo.insert_many(Repo.__mongo_pool__, "my_collection", documents)
```

**Comment by brado** [comment]
Sweet! Thanks for the speedy reply....I'll look into using this technique.
