### ISSUE TITLE
Primary, Secondary and stepdowns

### ISSUE THREAD

**Issue by fcruxen** [michalmuskala/mongodb_ecto#71]
I am using compose for the MongoDB provider and last night there was a stepdown, so primary and secondary changed roles. Unfortunately the mongo driver wasn't able to detect the change, and kept trying to write on the secondary (which was the primary before). I am separating manually read/write repos, so this behaviour was kindda expected. Is there anyway I can configure mongodb_ecto to automatically detect the stepdown and change write/read targets?

**Comment by tomjoro** [comment]
Duplicate of issue in mongodb driver (which mongodb_ecto uses) to support this: ericmj/mongodb#35. There is a workaround to use mongos, take a look.

**Comment by fcruxen** [comment]
terribly sorry, should have checked the tickets first. gonna close this one. thanks for the hint.
