### ISSUE TITLE
Support for the $last operator

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#72]
I have a MongoDB query which uses the $last operator, as in: 
```
db.sales_data.aggregate(
   [
     { $sort: { myobj_id: 1, update_date: 1 } },
     {
       $group:
         {
           _id: "$myobj_id",
           lastSalesDate: { $last: "$update_date" }
         }
     }
   ]
)
```
According to MongoDB doc, the $last operator has to occur in the scope of a $group aggregation. Does mongodb_ecto support a way to accomplish the query above? If it does not, is there a way to send a raw MongoDB query vs. using Ecto syntax? I don't know whether this is a mongodb_ecto feature, bug, or HOWTO, but this seemed the most logical place to start. Your assistance is appreciated! Thanks.

**Comment by chrisjowen** [comment]
+1 for $near operator or raw query

**Comment by michalmuskala** [comment]
Hey. You can use `fragment` in the queries to use directly the mongodb syntax if there's something we don't support.

If you need even more, you can directly use the functions provided by `Mongo`. The pool that those functions require is called `YourApp.Repo.Pool`.
