### ISSUE TITLE
Inserting keyword lists as maps

### ISSUE THREAD

**Issue by scottmessinger** [michalmuskala/mongodb_ecto#76]
Hi!

I could be wrong, but it seems that I can't insert a keyword list if I've defined the field as a map. From what I can tell, the driver has support for this:
> Since BSON documents are ordered Elixir maps cannot be used to fully represent them. This driver chose to accept both maps and lists of key-value pairs when encoding but will only decode documents to lists. 
https://github.com/ericmj/mongodb#data-representation

First, am I right about this limitation? Second, if so, how hard is the fix? Is this something I could create a pull request for? I'd need a little direction as to where to look.

**Comment by ericmj** [comment]
Why do you need a specific document order?

**Comment by michalmuskala** [comment]
This is most probably Ecto limitation rather than `mongo_ecto`'s itself. 

I would expect that when ecto is casting a `map` type it expects a map :smirk: .
A possible solution is a custom `Ecto.Type` that will list `map` for it's `type/0` callback, but accept keywords alongside maps. I think that the adapter should handle it just fine.

**Comment by scottmessinger** [comment]
Thanks for the response @ericmj  and @michalmuskala!!

@ericmj : It's not necessary, but really helpful. I have a document which has a map of 300+ dates. Having the dates ordered **dramatically** helps with debugging. E.g. 
```js
{
  dates: {
    "2016-01-01" : { ... },
    "2016-01-02":  { ... },
    "2016-01-03":  { ... } ,
  }
}
```

@michalmuskala : I'll take a look at trying out a custom type. Thanks for the pointer! I'm going to close this for now and reopen if I run into any trouble with the custom type.
