### ISSUE TITLE
[ecto 2.0] Invalid expression for MongoDB adapter in select clause in query

### ISSUE THREAD

**Issue by nanohest** [michalmuskala/mongodb_ecto#79]
I took a stab at making support for ecto 2.0
So far, what i did was:  
```diff
git diff ../../lib/mongo_ecto.ex                                                                                                                                                                                                       ✱
diff --git a/lib/mongo_ecto.ex b/lib/mongo_ecto.ex
index eb9c299..927ad45 100644
--- a/lib/mongo_ecto.ex
+++ b/lib/mongo_ecto.ex
@@ -395,6 +395,14 @@ defmodule Mongo.Ecto do
   end

   @doc false
+  def child_spec(repo, opts) do
+    Supervisor.Spec.worker(__MODULE__, [repo,opts], [])
+  end
+
+  def dumpers(:binary_id, type), do: [type, Ecto.UUID]
+  def dumpers(_, type), do: [type]
+
+  @doc false
   def stop(pid, timeout) do
     ref = Process.monitor(pid)
     Process.exit(pid, :normal)
@@ -477,7 +485,7 @@ defmodule Mongo.Ecto do
   @read_queries [ReadQuery, CountQuery, AggregateQuery]

   @doc false
-  def execute(repo, _meta, {function, query}, params, preprocess, opts) do
+  def execute(repo, _meta, {_, {function, query}}, params, preprocess, opts) do
     case apply(NormalizedQuery, function, [query, params]) do
       %{__struct__: read} = query when read in @read_queries ->
         {rows, count} =
```
But, trying to run the simple example app, left me stuck at:  
```
** (Ecto.QueryError) Invalid expression for MongoDB adapter in select clause in query:

from w in Weather,
  where: w.prcp > 0.0 or is_nil(w.prcp),
  select: w

    (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:455: Mongo.Ecto.NormalizedQuery.error/2
    (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:52: Mongo.Ecto.NormalizedQuery.all/2
    (mongodb_ecto) lib/mongo_ecto.ex:489: Mongo.Ecto.execute/6
            (ecto) lib/ecto/repo/queryable.ex:129: Ecto.Repo.Queryable.execute/5
            (ecto) lib/ecto/repo/queryable.ex:41: Ecto.Repo.Queryable.all/4
```  
Inserting IEx.pry in NormalizedQuery.all/2, I'm getting:  
```iex
iex(1)> Simple.sample_query
Request to pry #PID<0.264.0> at /Users/kristian/code/elixir/src/mongodb_ecto/lib/mongo_ecto/normalized_query.ex:51

        params = List.to_tuple(params)
        query  = query(original, params, from)
    IEx.pry
        case projection(original, params, from) do
          {:count, fields} ->

Allow? [Yn]

Interactive Elixir (1.2.3) - press Ctrl+C to exit (type h() ENTER for help)
pry(1)> from
{"weather", Weather, :id}
pry(2)> params
{}
pry(3)> query
%{"$or": [[prcp: ["$gt": 0.0]], [prcp: nil]]}
pry(4)>
```  
For the fun of it, I tried debugging the sample app with ecto 1.0.
This gives me the exact same values in {from,params,query}, but runs fine.  
  
Does anybody see what I am missing here?

**Comment by nanohest** [comment]
Did a small debugging session with erlang dbg last night (special thanks goes to [qhool/quaff](https://github.com/qhool/quaff)).
I debugged side by side with ecto 1.0 and ecto 2.0.
It turns out, that when it hits:
```elixir
defp projection(%Query{select: %Query.SelectExpr{fields: fields}} = query, params, from),
    do: projection(fields, params, from, query, %{}, [])
```
the value of 'fields' is different.
With ecto 1.0: `{'&',[],[0]}`
With ecto 2.0: `[{'&',[],[0,[id,city,temp_lo,temp_hi,prcp,inserted_at,updated_at],7]}]`
While Ecto 1.0 continues fine, this results in Ecto 2.0 ending up in
```elixir
  defp projection([{op, _, _} | _rest], _params, _from, query, _pacc, _facc) when is_op(op) do
    error(query, "select clause")
  end
```
So I guess that explains the "Invalid expression" error message.

Has anybody got a clue to what may go wrong, and where to look to fix this?

One other thing that is nagging me, is that when running with Ecto 1.0, it calls:
`def dump(type, data), do: Ecto.Type.dump(type, data, &dump/2)`
So I wonder whether it has to do with my crude implementation of dumpers/2, but I can't see how that makes a difference to the value of 'fields'.
Any opinions on that?

**Comment by michalmuskala** [comment]
Hello, I'm sorry it took me so long to get back to you.

Yes, it looks like Ecto 2.0 changed the format of the select field by adding all the fields inline. This is a rather good change for us, as we extract that data today ourselves here: https://github.com/michalmuskala/mongodb_ecto/blob/master/lib/mongo_ecto/normalized_query.ex#L150-L153

Dumpers probably does not affect that particular part, it will affect how we cast data types, but that is next step.

**Comment by nanohest** [comment]
No sweat.
Anyway, your comment was enough for me to realise the little something that I'd been missing. Pattern matching. So I made another projection, like this:
```elixir
defp projection([{:&, _, [0,fields,_]} = field | rest], params, {_, model, pk} = from, query, pacc, facc) do
    pacc = Enum.into(fields, pacc, &{field(&1, pk), true})
    facc = [field | facc]

    projection(rest, params, from, query, pacc, facc)
  end
```
Which seems to do the trick, but left me at:
```
** (UndefinedFunctionError) undefined function Simple.Repo.log/1
          (simple) Simple.Repo.log(%Ecto.LogEntry{connection_pid: nil, decode_time: nil, params: [], query: #Function<11.10125602/1 in :dbg_ieval.expr/3>, query_time: 963, queue_time: 39, result: {:ok, %Mongo.ReadResult{cursor_id: 0, docs: [%{"_id" => #BSON.ObjectId<570b6e781412e60d4ddcc42d>, "city" => "cph", "prcp" => 100.5, "temp_hi" => 35.0, "temp_lo" => 15.0}, %{"_id" => #BSON.ObjectId<570b6e801412e60d4ddcc42e>, "city" => "cph", "prcp" => 210.1, "temp_hi" => 35.0, "temp_lo" => 15.0}, %{"_id" => #BSON.ObjectId<570b6e8b1412e60d4ddcc42f>, "city" => "cph", "prcp" => 210.1, "temp_hi" => 18.0, "temp_lo" => 10.0}, %{"_id" => #BSON.ObjectId<570b6e981412e60d4ddcc430>, "city" => "cph", "temp_hi" => 18.0, "temp_lo" => 10.0}], from: 0, num: 4}}})
         (mongodb) lib/mongo/pool.ex:144: Mongo.Pool.run_with_log/5
         (mongodb) lib/mongo/cursor.ex:33: anonymous fn/6 in Enumerable.Mongo.Cursor.start_fun/6
          (elixir) lib/stream.ex:1084: anonymous fn/5 in Stream.resource/3
          (elixir) lib/enum.ex:1477: Enum.reduce/3
          (elixir) lib/enum.ex:1155: Enum.map_reduce/3
    (mongodb_ecto) Elixir.Mongo.Ecto.erl:508: Mongo.Ecto.execute/6
```
And I really don't get why. I would have thought Ecto.Repo implemented such log/1.
But I guess I'll find out after work.

**Comment by michalmuskala** [comment]
Ecto 2.0 changed how logging is done. The `log` function is definitely gone, but I'm not sure what replaced it from the perspective of an adapter. You could try disabling logging for now (commenting out the logging code).

**Comment by fishcakez** [comment]
For logging the adapter needs to call `repo.__log__/1` with `Ecto.LogEntry` as argument. The repo then needs to be configured with `loggers: [{mod, fun, args}]`. The `mod, fun, args` is called as `apply(mod, fun, [%Ecto.LogEntry{} | args])` and must return `Ecto.LogEntry` to be used for the next logger.

**Comment by michalmuskala** [comment]
Closing in favour of the PR: https://github.com/michalmuskala/mongodb_ecto/pull/84
