### ISSUE TITLE
Use custom name for collection created in MongoDB

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#81]
I am using a Phoenix web app, and I have several models that have the same name, but are differentiated by namespace, i.e.: 

System1.MyModel
System2.MyModel

This works fine with paths within the code and the URL routes available. The problem is that I need to be able to have the data associated with these models stored in different collections in MongoDB. I'd like it if the System1.MyModel model persisted to a system1_mymodel collection in MongoDB. Is it possible to make this happen? 

Thx.

**Comment by michalmuskala** [comment]
The name of the collection is whatever you pass to the `schema` call. It doesn't have to map 1-to-1 to the module name.
