### ISSUE TITLE
Is adapter: Mongo.Ecto still required in Repo definition?

### ISSUE THREAD

**Issue by brado** [michalmuskala/mongodb_ecto#82]
I created a new Phoenix web app project today and noticed that the generated project does not have this included in the Repo definition, as per the mongodb_ecto README: 

```
# In your application code
defmodule Repo do
  use Ecto.Repo,
    otp_app: :my_app,
    adapter: Mongo.Ecto
end
```

I did not add this, but tested my new project against MongoDB without this. I could see no problem with functionality -- I could read / write from MongoDB just fine. Is this still required, and what is the expected difference of having: 

adapter: Mongo.Ecto

vs. not having it? 

Thanks....

Brad

**Comment by michalmuskala** [comment]
You can either have it in the repo or in the config. Either one is acceptable.
