### ISSUE TITLE
Ecto 3.0 support

### ISSUE THREAD

**Issue by omouse** [michalmuskala/mongodb_ecto#83]
it looks like the mix.exs file has to be updated to support Ecto 3.0?

**Comment by ericmj** [comment]
I think you mean Ecto 2.0 :). But the library does not support 2.0 yet so we shouldn't update the mix.exs file.

**Comment by omouse** [comment]
ah ok, yeah I'm new to this and wasn't sure what the dependencies are. Thanks for explaining!

**Comment by michalmuskala** [comment]
The work is being done in the PR https://github.com/michalmuskala/mongodb_ecto/pull/84
