### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by merqlove** [michalmuskala/mongodb_ecto#86]
warning: function Mongo.Ecto.rollback/2 is undefined or private
warning: function Mongo.Ecto.transaction/3 is undefined or private

M.E version: master
Ecto: 1.0.0
Elixir: 1.3.0

**Comment by michalmuskala** [comment]
Yeah, it makes sense they are there, but I'm not sure how we could go about fixing them.

A hotfix for now would probably be to define `rollback` and `transaction` in your repo to avoid ecto generating the default implementation:
```elixir
def transaction(_, _), do: raise "not supported"
def rollback(_), do: raise "not supported"
```

I will think of a general solution in ecto

**Comment by merqlove** [comment]
Yeah, these wrappers sit in Ecto.Repo adapter. 
No, it cannot help:) Elixir looking for those methods in Mongo.Ecto, because it's called via Ecto adapter.
I think we can wait, seems you have started new branch for 2.0., maybe it can be fixed with its release, no matter when it will be.

**Comment by michalmuskala** [comment]
This is an issue in ecto itself, that is still present in master. Tracked in https://github.com/elixir-ecto/ecto/issues/1530. I'll close this issue for now.
