### ISSUE TITLE
Mongo tcp error: closed

### ISSUE THREAD

**Issue by agusguerra10** [michalmuskala/mongodb_ecto#87]
Hey Michal, I'm getting a "Mongo tcp error: closed" once in a while. Any idea about what could be causing this? Thanks in advance.

Agus.

**Comment by michalmuskala** [comment]
This looks like a dropped connection, it might be that the connection to the database is not stable

**Comment by agusguerra10** [comment]
Thank you Michal. I guess it's mLab free service not working very well.

Regards.

**Comment by Morganjackson** [comment]
@agusguerra10 Did you end up getting this to work? I'm having the same issue using compose.io

It seems like a common issue when using mongo remotely. https://github.com/michalmuskala/mongodb_ecto/issues/52

@michalmuskala do you have any ideas on what might be causing this? it usually works for 2 - 5 minutes and then I get the error below:

```
[error] #PID<0.687.0> running Demo.Endpoint terminated
Server: johndoe.localhost:4000 (http)
Request: GET /
** (exit) exited in: GenServer.call(#PID<0.542.0>, {:find, "users", [{"$query", [username: "johndoe"]}, {"$orderby", %{}}], %{_id: true}, [batch_size: 1000]}, 5000)
    ** (EXIT) time out
[error] Mongo tcp error (galaga.3.mongolayer.com:10161): connection timed out
[error] Mongo tcp error (galaga.3.mongolayer.com:10161): closed
```

I have tried increasing the timeout but it didn't make any difference.
