### ISSUE TITLE
News on Ecto 2.0 support?

### ISSUE THREAD

**Issue by agusguerra10** [michalmuskala/mongodb_ecto#89]
Hey Michal, any news about upgrading the package to support Ecto 2.0? I'm trying to use scrivener_ecto but it requires Ecto 2.0.

Thanks!

Agus.

**Comment by michalmuskala** [comment]
This is still in the works. Unfortunately, this was not my priority lately. You can follow the progress in the PR https://github.com/michalmuskala/mongodb_ecto/pull/84
