### ISSUE TITLE
Support for aggregates in queries

### ISSUE THREAD

**Issue by michalmuskala** [michalmuskala/mongodb_ecto#9]
Currently the adapter supports only the most basic queries, that simply retrieve documents from the database.

But there is much more we can do using [aggregates](http://docs.mongodb.org/manual/reference/command/aggregate/) - counts, groups, more fine-tuned matching or odering and document transformation.

What I'm not sure about is whether the normal adapter callbacks should support only simple queries, and more advanced ones should be allowed through some other mechanism, or maybe the adapter should detect if an advanced query is needed and prepare it - all with the normal functions.

**Comment by josevalim** [comment]
count in particular is supported in SQL adapters and other aggregators. I don't think we have an integration test for it, so we need to discuss how those things will look like.

**Comment by josevalim** [comment]
The issue here, though, is that the aggregation API in mongo uses a different query syntax, right? We cannot just mix them into Ecto.Query as SQL does, right?

**Comment by michalmuskala** [comment]
I've added support for `count` in https://github.com/michalmuskala/mongodb_ecto/commit/ff97d696958e571772b5284d32f47d20acd68c27 as much as it's possible in MongoDB

**Comment by michalmuskala** [comment]
Support for `min`, `max`, `sum` and `avg` similar to `count` is in master.
