### ISSUE TITLE
Is Ecto 2 supported?

### ISSUE THREAD

**Issue by mrkaspa** [michalmuskala/mongodb_ecto#92]

**Comment by bAmpT** [comment]
Please have a look here: @ #91 #84

**Comment by mrkaspa** [comment]
@bAmpT great I need this urgent in a project

**Comment by michalmuskala** [comment]
The work is being done in the mentioned PRs. If you want to speed it up, you can help with the update. Unfortunately, because of other obligations, this is not a priority for me at the moment.

**Comment by ankhers** [comment]
@mrkaspa The adapter is not 100% finished, but I am already using it in a project of mine. Depending on the parts of the adapter you need, you may already be able to use in its current state.
