### ISSUE TITLE
module Mongo.Pool is not loaded and could not be found

### ISSUE THREAD

**Issue by agiuliano** [michalmuskala/mongodb_ecto#99]
Hi there, I was trying to install Phoenix with mongodb_ecto, but when I try to run mix deps.get I got back
```
== Compilation error on file lib/mongo_ecto/admin_pool.ex ==
** (CompileError) lib/mongo_ecto/admin_pool.ex:4: module Mongo.Pool is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/mongo_ecto/admin_pool.ex:4: Mongo.Ecto.AdminPool (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

my database configuration are the following:
```
config :my_app, Hogwarts.Repo,
  adapter: Mongo.Ecto,
  database: "my_app",
  pool_size: 1
```

I also tried to remove the `pool_size` but still have this issue

**Comment by ericmj** [comment]
Use an older version of mongodb, add `{:mongodb, "~> 0.1.0"}` to your dependencies.

**Comment by michalmuskala** [comment]
I've just released 0.1.5, which has a stricter dependency on mongodb, and should fix this issue.

**Comment by tacnoman** [comment]
I'm having big troubles with versions. When I make a downgrade in a lib, there is another conflict.
Someone could send me an example of method `deps` in a new started project?

Ex:
```elixir
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:mongodb_ecto, "~> 0.1.5"},..........
    ]
  end
```

**Comment by ericmj** [comment]
@tacnoman You need to use an older phoenix_ecto to get an ecto version compatible with mongodb_ecto. Try: `{:phoenix_ecto, "~> 1.0"}`.
